- include_role:
    name: btn.dns.post
  vars:
    obj_type: b1_ipam_subnet
    host: https://csp.infoblox.com
    api_key: "{{ lookup('ansible.builtin.env', 'CSP_API_KEY') }}"
    space: "Public IP"
    address: "{{ info['network'] | ansible.utils.ipaddr('network/prefix') }}"
    name: ""
    comment: "{{ info['device'] }}"
    tags:
      - "ResourceType": "PublicIPRange"
      - "ResourceUseCase": "DMZ"
      - "ResourceOrigin": "DirectAccess"
    state: present
  rescue:
    - debug:
        msg: "Error occured for network - {{ info['network'] | ansible.utils.ipaddr('network/prefix') }}" 
