---
collections:
  - name: git@github.com:sf-bt-neteng-emu/ansible-collection-btn-dns.git
    type: git
    version: main
  - name: git@github.com:infobloxopen/bloxone-ansible.git#ansible_collections/infoblox/b1ddi_modules
    type: git
    version: main