- block:
  - include_role:
      name: btn.dns.post
    vars:
      obj_type: b1_ipam_ipv4_reservation
      host: https://csp.infoblox.com
      api_key: "{{ lookup('ansible.builtin.env', 'CSP_API_KEY') }}"
      space: "Public IP"
      address: "{{ info['ip'] }}"
      name: "{{ info['location'] }} - {{ info['device'] }}"
      comment: "Type: {{ info['type'] }}"
      tags:
        - "ResourceAssignment": "Type"
        - "ResourceUseCase": "Firewall"
      state: present
  rescue:
    - debug:
        msg: "Error occured for network - {{ info['network'] }}" 