---
- name: Firewalls IPAM Setup
  block:
    - set_fact: 
        dummy: "some_dummy_fact"

    - debug: msg="{{ dummy | get_fw_ips }}"
      register: result

    - set_fact:
        public_ips: "{{ result['msg'] }}"

    - name: Loop over the result and create/update required networks
      include_tasks: create_subnet.yml 
      vars:
        info: "{{ item }}"
        source: "firewalls" 
      loop: "{{ public_ips }}"