---
- name: Cloudgenix IPAM Setup
  block:
    - name: Get public IPs from cloudgenix
      btn.cloudgenix.public_ips:
        token: "{{ lookup('ansible.builtin.env', 'CLOUDGENIX_TOKEN') }}"
      register: result
      
    - set_fact:
        public_ips: "{{ result['output'] }}"

    - name: Loop over the result and create/update required networks
      include_role:
        name: btn.dns.post
      vars:
        obj_type: network
        host: phx-gridm-ap001.internal.salesforce.com
        username: "{{ lookup('ansible.builtin.env', 'IPAM_USERNAME') }}"
        password: "{{ lookup('ansible.builtin.env', 'IPAM_PASSWORD') }}"
        network: "{{ item['network'] | ansible.utils.ipaddr('network/prefix') }}"
        network_view: "PubIPs"
        state: present
      loop: "{{ public_ips }}"
